# Generated by Django 6.0.1 on 2026-03-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipe_createdon_recipe_updatedon_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='ledger.profile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
