# Generated by Django 6.0.1 on 2026-03-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_recipe_author_alter_recipe_createdon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shortBio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='ledger.profile'),
        ),
    ]
