# Generated by Django 6.0.1 on 2026-03-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_profile_shortbio_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='shortBio',
            new_name='short_bio',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='updatedOn',
            new_name='updated_on',
        ),
    ]
